GET http://localhost:8080/cards

###

POST http://localhost:8080/cards  HTTP/1.1 content-type: application/json

{
    "cardName": "Savannah Lions",
    "colors": "White",
    "manaValue": "1",
    "type": "Creature",
    "subtype": "Cat",
    "stats": "2/1",
    "text": "N/A"
}
###

POST http://localhost:8080/decks HTTP/1.1 content-type: application/json

{
    "deckName": "White Weenies", 
    "card1Name": "Plains", 
    "card1Number": "20",
    "card2Name": "Savannah Lions",
    "card2Number": "4"
}